### ISSUE TITLE
Norwegian support for "Today" and "Tomorrow" 

### ISSUE THREAD

**Issue by stianhoe** [bruxy70/Garbage-Collection#117]
**Is your feature request related to a problem? Please describe.**
I get english text when state is 0 or 1 (today or tomorrow)

**Describe the solution you'd like**
Can you add support for norwegian as well?
Tomorrow="I morgen"
Today="I dag"

**Additional context**
Great product! Exactly what I needed.

**Comment by bruxy70** [comment]
Thanks. Will be in the next release - with the fix of #118

**Comment by KrzesloSzatan** [comment]
@bruxy70 Where can i change it myself to change those words to be in my language ? Or do you prefer to create another request with Polish words in it ?

**Comment by bruxy70** [comment]
The best would be to make sensor.pl.json here https://github.com/bruxy70/Garbage-Collection/tree/development/custom_components/garbage_collection/.translations
(copy sensor.en.json and replace the right side with English words - you can look how the other languages are done). And then make a pull request to upload the file to the git repository, so that  others can use that as well.
There is also the file <language code>.json, that provides translation for the web interface configuration. That is optional, but if you want to look at that too, that would be nice :). Thanks.

**Comment by KrzesloSzatan** [comment]
Im not fluent in git so i think i've done it, dunno if the proper way tho ;) If its ok i will take a look on the other .json you mentioned

**Comment by bruxy70** [comment]
Thanks. Great. Merged. Will be included in the next release.
If you want to use it before that, just put the file locally in your home assistant.

**Comment by KrzesloSzatan** [comment]
The poroblem is I have installed it with HACS and if it should be places in .../custom_components/garbage_collection/.translations there is no such folder in my case. Wondering if it will be OK if i just create it and place those files there ?

**Comment by bruxy70** [comment]
It should be there. Maybe you need to enable hidden files?

**Comment by KrzesloSzatan** [comment]
![obraz](https://user-images.githubusercontent.com/63119934/78783469-f8431f00-79a3-11ea-9d9a-933761c7a006.png)

**Comment by bruxy70** [comment]
Ok, I made a beta release 2.20-beta. So enable beta versions in HACS and you can upgrade it.

**Comment by KrzesloSzatan** [comment]
Too quick, im on the other translation ;) Will upload when finished
