### ISSUE TITLE
paper collected

### ISSUE THREAD

**Issue by compujunk** [bruxy70/Garbage-Collection#172]
with us the paper is collected every month during the last full working week, for example:
Jan 28
Feb 25
March 24
April 28
May 26
June 23
How can this be configured since it is not a fixed number of days and not really monthly

**Comment by bruxy70** [comment]
One way would be to aim for the first Sunday each month (which means that the previous week was always a full week). And then use a template sensor to decrement a number of days from that date (I think 12 in your case).
Would that work?

**Comment by uherting** [comment]
> How can this be configured since it is not a fixed number of days ...
I've got no idea how to get this done with this add-on. 
But maybe I've got a solution for you. A while ago I came across the HACS integration called "ICS" which works with Google calendar. One can have several sensors who are based on a keyword in the title of the calendar entry.
There is also a add-on/ integration which displays a Google calendar, for details please see https://youtu.be/6bwUfNMVT24 .

**Comment by bruxy70** [comment]
Yes, you can use google calendar integration. It is a standard part of HA.

But I guess the idea with "offset" would work as well. If you set a sensor for 1st Sunday each month, it will always be that the the month is starting somewhere in that week - worst case Sunday. So that the previous week was always the last full week. So if you'd go for {{ (as_timestamp(state_attr('sensor.entity_name','next_date')) - 7*60*60*24) | timestamp_local  }}, it will be Sunday of the last full week of the month. 12*60*60*24 will get you 5 days before that, that is always Tuesday of the last full week of the month.
