### ISSUE TITLE
Extra collection dates

### ISSUE THREAD

**Issue by NielsFeenstra** [bruxy70/Garbage-Collection#2]
In the netherlands they have extra pick up dates for the vegetable waste. Is it possible to create extra pickup dates for the same sensor.

Now I have a extra sensor for the extra dates.

**Comment by bruxy70** [comment]
For each sensor you can have multiple days, for example on Tuesday and Thursday.  That probably makes sense mostly for weekly schedule. Is that what you meant? Or did you mean something like "every 1st and 3rd Wednesday each month?" That I currently do not have implemented.
What you could do now is, you can have two sensors, and them combine them with a template sensor (e.g. what we have here is, large waste collection 1st Saturday each month, and also every 3rd during the summer months - and for this, I did exactly that, otherwise the configuration would be quite complicated.

**Comment by NielsFeenstra** [comment]
I think that combining 2 sensor is the most simple solution for my problem. The extra pickup dates are only a few months in the summer.
A second frequency would be a complicated configuration.

Maybe it's possible to add extra dates in the configuration and disabled dates (like christmas), something like this:

  - platform: garbage_collection
    name: papiercontainer
    frequency: "even-weeks"
    collection_days:
    - thu
    extra_dates:
    - 09/04/19
    - 09/18/19
    - 12/23/19
    disabled_dates:
    - 12/25/19

**Comment by bruxy70** [comment]
Ok, I will close the issue then. If you'd like more flexibility on the schedule, you can schedule recurrent events in google calendar, add and remove exceptions and use the google calendar component in Home Assistant.

**Comment by bruxy70** [comment]
I did add the option to exclude dates and include extra days in the latest release.
