### ISSUE TITLE
Did version 0.116 brake integration?

### ISSUE THREAD

**Issue by alfiro** [bruxy70/Garbage-Collection#205]
It seems that latest version  0.116.0 brake the integration. 
After restart HA now it shows following error: 

![2020-10-08_13h04_31](https://user-images.githubusercontent.com/9274097/95490848-d3396400-0966-11eb-9bd5-93cc6cf6ebee.jpg)
)

**Comment by bruxy70** [comment]
Works fine here. It complains about the missing card, not the integration BTW.

**Comment by alfiro** [comment]
But it didn't change anything and it is showing this error. 
How can I fix it?
Thank you in advance for your help.

**Comment by bruxy70** [comment]
To check if the integration is working or not,  go to the developer tools, states and check if the sensor sensor.regular_waste is there. If not, check the error log and let me know.

Otherwise, close the ticket and ask the author of the custom garbage collection card. He would not receive of you opened it here.

**Comment by alfiro** [comment]
Thank you so much, Sensor is there. 
I will close the issue and report to the author.
Thank you so much for your help.
