### ISSUE TITLE
Allow user to select first day of the week:

### ISSUE THREAD

**Issue by PrayerfulDrop** [bruxy70/Garbage-Collection#222]
Currently the application is assuming Sunday is the first day of the week.  In the US garbage days usually start on Mondays not Sundays.  July 2021, Independence day in the States is on a Sunday and the Garbage Collection app is moving the garbage day forward a day when it should not.  Also, majority of trash companies in the US do not work on Sundays.

Suggested solution: Option to ignore Sundays **OR** allow user to set first day of the week.

![image](https://user-images.githubusercontent.com/999665/103033403-ffa55b00-4527-11eb-9b66-d5110dc483b3.png)

**Comment by bruxy70** [comment]
What is your configuration and what is your expected behavior? These questions are in the template for a reason.
No, the integration does not assume that the first day of the week is Sunday. You actually specify the collection day by day name, not day number, so I am not sure what is the issue.
As for the week numbers, it uses the [ISO definition](https://en.wikipedia.org/wiki/ISO_8601#Week_dates) - which counts the week with the first Thursday in it as a week number 1. And this is really used for collection every-n-weeks/off/even weeks, that work with the week number. Which might not be that useful as it resets at the beginning of each year. Collection every-n-days might be more useful as it continues from last year.

**Comment by bruxy70** [comment]
And if your issue is, that it is skipping a holiday and moving it to the next day, which is Saturday, then you can configure that with holiday_move_offset and set it to 3, then it moves to Monday.

**Comment by bruxy70** [comment]
And if you refer to how the calendar is displayed, then this has nothing to do with this integration, this is how Home Assistant displays it in general. It is a generic functionality, it displays all calendars this way and you cannot configure that unfortunately (which sucks, as in Europe, the weeks start from Monday - but HA is hard-coded to show the American calendar).

**Comment by PrayerfulDrop** [comment]
Sorry about the late reply.  The offset doesn't help either.  This is a logic issue unfortunately due to how garbage pickup is done in the USA.  

If a holiday falls on a Saturday or Sunday then the garbage collection is not affected and the day for garbage pickup remains the same.  Currently, your calendar logic for the USA doesn't take this into account.  July 4th, 2021 falls on a Sunday.  But in garbage application it is moving the normal pickup ahead a day.  You can see this in the screen snip below.  

Hope this makes sense.

![image](https://user-images.githubusercontent.com/999665/103470202-048eb980-4d35-11eb-854c-6086c21dc7b3.png)

**Comment by bruxy70** [comment]
That must be something else. The holiday in week move should look for the holidays from Monday to collection day, it should not be affected by a holiday on Sunday. Can you please enable debugging and send me the debug log. It will list the used list of holidays and the message that it is moving the collection for July 9 because of the holidays in that week. Or send me the exact configuration and I will try to replicate it. Right now, I have no idea what is going on. Thanks!

**Comment by bruxy70** [comment]
Looking at the holidays it returns for the US for this year:
``2021-01-01: New Year's Day
2021-12-31: New Year's Day (Observed)
2021-01-18: Martin Luther King Jr. Day
2021-02-15: Washington's Birthday
2021-05-31: Memorial Day
2021-07-04: Independence Day
2021-07-05: Independence Day (Observed)
2021-09-06: Labor Day
2021-10-11: Columbus Day
2021-11-11: Veterans Day
2021-11-25: Thanksgiving
2021-12-25: Christmas Day
2021-12-24: Christmas Day (Observed)``

Could it be, that it skips the holiday because of 2021-07-05: Independence Day (Observed)
I've found that 
``Independence Day is a federal holiday. If July 4 is a Saturday, it is observed on Friday, July 3. If July 4 is a Sunday, it is observed on Monday, July 5``. So this is what the library I use finds. So perhaps disabling the observed holidays would help?

**Comment by PrayerfulDrop** [comment]
That was it!  Observed holidays force the date to move.  This is very much appreciated!
