### ISSUE TITLE
n-th day of the month

### ISSUE THREAD

**Issue by wvoigt** [bruxy70/Garbage-Collection#258]
**How do I set it up to do the nth day of the month?  
As a bonus, the nth day of the month, but if it falls on a weekend, the Friday before.  
Also, I'm assuming the last day of the month can be -1 offset from the first day of the next month? .

My end goal is the 15th and the last day of the month, but moved to the Friday before if it lands on a Saturday or Sunday.**

**Comment by bruxy70** [comment]
The nth day of the month is not an option. I suggest using a calendar for that. It also does not deal with weekends (whatever weekend is - it is different in different countries) - since most of the schedules are based on a specific day of a week (as this is used for garbage collection usually). So if the schedule is set for let's say Wednesday, you know that it is not a weekend.
