### ISSUE TITLE
Wrong days

### ISSUE THREAD

**Issue by djbombacz** [bruxy70/Garbage-Collection#263]
**Describe the bug**
What is wrong?
-->

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 
Config Flow

```yaml

```

**Error log/debug information**

```txt

```

**Screenshots**
![Snímek obrazovky 2021-04-22 v 19 29 34](https://user-images.githubusercontent.com/77015066/115913633-29887300-a471-11eb-8f61-73bf471eee6e.png)

**Version**

Integration version: latest

Home Assistant version: Home Assistant 2021.4.6

**Comment by bruxy70** [comment]
I do not understand what is the problem and how to replicate it, and I do not know what is the configuration.
From the picture it looks like there was a scheduled collection for April 22nd that expired at 6pm. So that now the next collection is scheduled for May 6th, that is in 14 days. All looks ok.

**Comment by djbombacz** [comment]
Yes, all is OK. I am from czech republic. Is possible you send e-mail? Thanks

**Comment by bruxy70** [comment]
Yes, you can send me an email. But if this is about describing and resolving this issue, then do it here. Thanks.
