### ISSUE TITLE
1st Friday in Month is wrong

### ISSUE THREAD

**Issue by jankete** [bruxy70/Garbage-Collection#265]
**Describe the bug**

I configured a sensor being active on "1st Friday in month". It shows the next date as "2021-04-30" which is obviously not the first Friday.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 
Config Flow

![image](https://user-images.githubusercontent.com/22338766/116033327-821e6280-a661-11eb-8952-78b23e5f0ff4.png)
![image](https://user-images.githubusercontent.com/22338766/116033359-8f3b5180-a661-11eb-9700-adf22ee5c127.png)
![image](https://user-images.githubusercontent.com/22338766/116033392-9c584080-a661-11eb-970e-ff61fa570858.png)

**Error log/debug information**

```txt

```

**Screenshots**

![image](https://user-images.githubusercontent.com/22338766/116033445-b3972e00-a661-11eb-8e69-119905c72b64.png)

**Version**

Integration version: 3.17
Home Assistant version: core-2021.4.6

**Comment by bruxy70** [comment]
You have configured it to use the number of week, instead of number of weekday. 
So it is not first Friday of month but the Friday first week of the month. And 1st is on Sunday, so it counts as first week.
I do not understand the use of this as well, I agree it looks confusing, but this was sent as a PR and number of users asked for it, so it apparently is needed. Not sure what for.
Anyhow, just uncheck this option and you should be fine. 
Did you configure it that way on purpose? Why? I do not think this is a default option. Is the documentation unclear? If it is, can you suggest a better wording?

**Comment by jankete** [comment]
I think, it was just a mistake setting this. After removing it, it works as expected. Thanks!
