### ISSUE TITLE
Blueprint: Move the collection to the PREVIOUS day, if the collection falls on public holiday

### ISSUE THREAD

**Issue by novitibo** [bruxy70/Garbage-Collection#368]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi, great addon! Respect!
I have only one question:
How can we Move the collection to the PREVIOUS day, if the collection falls on public holiday?
TNX!!!

**Comment by bruxy70** [comment]
You can change the automation or the blueprint to move the date back, instead forward. Is that something you can do, or you want some help with that?

**Comment by novitibo** [comment]
I used the automation untill I discovered your blueprint to move the collection one day after the holiday.
What blueprint should I use to move collection to a day before holiday?

**Comment by bruxy70** [comment]
I do not think there is a blueprint for that. I think you can take one and modify it. Or I can do that for you :). But for that I'd need to know how is that supposed to work. There are currently different flavors.  The basic one just moves the collection I it falls on holiday. But then it checks if the new day also is not a public holiday, if it is, it keeps moving it forward. This is the move_on holiday blueprint. So if we can start from there, we can basically use it without a change, but deduct the offset instead of adding it (so a change on 4th and the last line). So it will be something like:
```yaml
              {%- set collection_date = as_datetime(trigger.event.data.collection_dates[repeat.index-1]) %}
              {%- set ns = namespace(offset=-1, found=false) %}
              {%- for _ in range(7) if not ns.found %}
                {%- set d = ( collection_date - timedelta( days=ns.offset) ) | as_timestamp | timestamp_custom("%Y-%m-%d") %}
                {%- if d in state_attr(holiday_entity,'holidays') %}
                  {%- set ns.offset = ns.offset + 1 %}
                {% else %}
                  {%- set ns.found = true %}
                {%- endif %}
              {% endfor %}
              {{ -ns.offset }}
```
There are other variants, dealing with a holiday earlier in the week, and possibly carry over to the following week, if there were multiple holidays, but I do not think this is what you want.
