### ISSUE TITLE
trenslate 

### ISSUE THREAD

**Issue by ProBreizh** [bruxy70/Garbage-Collection#404]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hello,
I have configured 2 garbage cans, but when it's the day, instead of having the translation franch, I have them in English. I have configured everything via the gui.

It's not really annoying for me, but the kids don't understand English, they are still too young.

Could you explain me how to apply the translation? 

Thanks

**Comment by bruxy70** [comment]
Hi,
First, the translation might not depend on this integration at all - in general, the integration works for entire system on the "back end" and it just changes the values of the entities. The translation is then done by the card that shows them on your screen, that might be even different for each user based on the language they configured. And I do not know what card you use , so that might be that.

Said tat, I made one exception, as many people asked for it. There is the "verbose state" you can configure for the sensor. Then, it will render the state in text, based on the language you selected in your system. So it translates words today and tomorrow. And there is a "template" where you can specify how to format the text saying in how many days is the collection. So that might be another option.

**Comment by ProBreizh** [comment]
hi,
thank you for your answer
