### ISSUE TITLE
Integration needs more than 3 minutes to start

### ISSUE THREAD

**Issue by SKis274** [bruxy70/Garbage-Collection#426]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi there,

I hope you're doing well. 

Is it normal that the integration needs so much time to start?
![image](https://user-images.githubusercontent.com/97400963/190441248-ccf7fe78-3150-4525-b450-3032092d780c.png)

If not how can I reduce it? I have seven garbage collection helpers running on my instance and also 5 automations to include/exclude some dates.

Thanks a lot and best regards!

**Comment by bruxy70** [comment]
Yes, this si normal. These are not time critical, since they only update on date change - on midnight. So the aim is to schedule them and update only when really necessary, to keep it light on the system. So there is a traffic light that only triggers the update when the date changes or the system is started.
