### ISSUE TITLE
General integration instead of one per schedule ?

### ISSUE THREAD

**Issue by poofyteddy** [bruxy70/Garbage-Collection#61]
Hello, Sorry to bother, this might have already been asked but i didn't saw it
When i use the UI to set up multiple garbage schedule, instead of having one integration with different device, i have one integration per schedule, with a single device.

Is this normal ? wanted ?

**Comment by bruxy70** [comment]
Yes, I know. I did not like it initially as well. I'd love that as I could have a common configuration and then configuration per sensor. I was challenging the team behind HA with this, it turns out there is no other way, it is not granular enough. So I got used to it.
Some integrations create multiple sensors with one integration, but this only works with physical devices. There is no way to do that for garbage collection, at least not now. Sorry

**Comment by poofyteddy** [comment]
thank's for the quick reply. I understand it's out of your hand :) having a UI way to set it up is already awesome !
