### ISSUE TITLE
Add start_date or start_year

### ISSUE THREAD

**Issue by pinkywafer** [bruxy70/Garbage-Collection#64]
**Is your feature request related to a problem? Please describe.**
I'm using the every_n_weeks option for a 3 weekly schedule. The schedule continues every 3 weeks over the years end, but as the only way to set the start date is with start_month and start_week, when the year rolls over, a 3 weekly schedule has a different start week, requiring a configuration change

**Describe the solution you'd like**
A start_year config option, or a start_date config option,  to allow a schedule to continue over the years end without reconfiguration 

**Describe alternatives you've considered**
Only option at the moment is to reconfigure annually 

**Additional context**

**Comment by bruxy70** [comment]
Just to make sure I understand how do you want it to work...
The way `every_n_weeks` schedule works today (and even and odd weeks as well for that matter) is, it tests if the week number - the `start_week` is divisible by n  (  (`week_number - start_week) % n == 0`) )
If it is divisible, the collection is this week, otherwise, the collection is in `n - (week_number - start_week) % n` weeks.
How should I incorporate the `start_year` parameter in the test?

**Comment by pinkywafer** [comment]
add 52 * number of years since start_year to current week number 

Something like:
```
number_of_years = current_year - start_year
(( week_number + (52 * number_of_years) - start_week) % n == 0)

**Comment by bruxy70** [comment]
Are you sure it will work?
The week number counts like that https://en.m.wikipedia.org/wiki/ISO_week_date - basically the first week of the year is the first week containing Thursday. 
If I add 52 to it next year and 104 in 2021....
I guess I can do that.

The other option I thought about was to simply add a parameter with start date, and simply count the number of weeks since then. But it would be comoletely separate frequency option then. I guess it could even be every n days since a date, so for 3 weeks you'd add 21 and a specific date and that would be it. WDYT?

**Comment by pinkywafer** [comment]
Thinking about it,  the every n days since date would probably be  better, especially since there is the occasional 53 week year.

**Comment by bruxy70** [comment]
Ok, will look at it next year ;)

**Comment by bruxy70** [comment]
Hi. `every-n-days` frequency included in the latest release. It takes 2 parameters to configure it: `first_date` (in YYYY-MM-DD format) and `period` (number of days).

**Comment by pinkywafer** [comment]
Fantastic. Thanks
